er_billeterie_homepage:
    path:     /
    defaults: { _controller: ERBilleterieBundle:Default:index }
    
er_billeterie_Client:
    path:   /client
    defaults:
        _controller: ERBilleterieBundle:Default:client
        
er_billeterie_paiement:
    path:   /paiement
    defaults:
        _controller: ERBilleterieBundle:Default:paiement
     
